version: "3"
services:
    app:
      image: webdevops/php-dev:alpine-php7
      volumes:
        - "./:/app"
      working_dir: "/app"
      links:
        - mariadb
        - mongodb
    mariadb:
      image: bitnami/mariadb
      ports:
        - "3310:3306"
      expose:
        - "3306"
      volumes:
        - "./demo/scripts:/docker-entrypoint-initdb.d"
      environment:
        MARIADB_HOST: "common"
        MARIADB_DATABASE: "common"
        MARIADB_USER: "common"
        MARIADB_PASSWORD: "common"
        MARIADB_ROOT_PASSWORD: "common"
        ALLOW_EMPTY_PASSWORD: "yes"
    mongodb:
      image: bitnami/mongodb
      expose:
        - '27017'
      environment:
        MONGODB_HOST: "common"
        MONGODB_USERNAME: "common"
        MONGODB_PASSWORD: "common"
        MONGODB_DATABASE: "common"
